import Head from "next/head";
import Image from "next/image";
import styled from "@emotion/styled";
import { Title } from "../components/global/Global";
import PokemonCard from "../components/global/PokemonCard";

const Card = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  border: 1px solid #ccc;
  border-radius: 0.5rem;
`;

const PokedexWrapper = styled.div`
  display: grid;
  gap: 1rem;
  grid-template-columns: 1fr 1fr;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Poképedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>My Pokémons</Title>
      <Title>Pokédex</Title>
      <PokedexWrapper>
        <PokemonCard
          id="1"
          image="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          name="Bulbasaur"
        />
        <PokemonCard
          id="2"
          image="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png"
          name="Ivysaur"
        />
        <PokemonCard
          id="3"
          image="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"
          name="Venusaur"
        />
      </PokedexWrapper>
    </div>
  );
}
