import { useEffect, useState } from "react";
import Image from "next/image";
import Head from "next/head";
import { useRouter } from "next/router";
import styled from "@emotion/styled";
import { Title, Subtitle } from "../../components/global/Global";
import pokemonNumber from "../../utils/pokemon-number";
import Button from "../../components/global/Button";
import TypesAndMoves from "../../components/pokemon-detail/TypesAndMoves";

const BannerWrapper = styled.div`
  display: flex;
  align-items: center;
  margin-top: -2rem;
`;

const InfoWrapper = styled.div`
  margin-left: 2rem;
`;

export default function PokemonDetail() {
  const router = useRouter();
  const [pokemon, setPokemon] = useState({
    id: "0",
    name: "",
    types: [],
    moves: [],
  });
  useEffect(() => {
    const { id } = router.query;
    setPokemon({
      id,
      name: "Bulbasaur",
      types: ["grass", "poison"],
      moves: ["tackle", "vine whip"],
    });
  }, [router.query]);
  return (
    <div>
      <Head>
        <title>Poképedia | {pokemon.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BannerWrapper>
        <Image
          src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemon.id}.png`}
          alt="pokemon"
          height={150}
          width={150}
        />
        <InfoWrapper>
          <Subtitle style={{ marginBottom: ".5rem" }}>
            {pokemonNumber(pokemon.id)}
          </Subtitle>
          <Title>{pokemon.name}</Title>
        </InfoWrapper>
      </BannerWrapper>
      <TypesAndMoves types={pokemon.types} moves={pokemon.moves} />
      <Button variant="contained">
        Catch
      </Button>
    </div>
  );
}
